const contacts = [
  "Alan Allman",
  "Anthea Alder",
  "Barry Benson",
  "Betty Boston",
  "Charles Champion",
  "Catherine Cameron",
  "Desmond Denton",
  "Deidre Dickson",
  "Eamonn Edwards",
  "Elsie Egbert",
  "Frank Friedman",
  "Fenella Frume",
  "Graham Gaskett",
  "Gertrude Garner",
  "Harry Hendrix",
  "Hermione Hoffman",
  "Isaac Ingram",
  "Isobelle Ignoble",
  "Jim Jeffrey",
  "Jane Jones",
  "Kenneth Kestrel",
  "Karli Karlson",
  "Luke Loffgrund",
  "Lesley Lomond",
  "Mick Munster",
  "Mary Marriott",
  "Nigel Nixon",
  "Nigella Newton",
  "Oswald Oscar",
  "Olivia Oswald",
  "Peter Peterson",
  "Penelope Pinter",
  "Quentin Quack",
  "Queen Quick",
  "Rick Ronson",
  "Rachel Robbie",
  "Steve Stone",
  "Sharon Stoppard",
  "Tony Target",
  "Tia Tricket",
  "Ulysses Upson",
  "Ursula Unsworth",
  "Victor Vent",
  "Verity Varnish",
  "Will Walsh",
  "Wendy Williams",
  "Xavier Xylophone",
  "Xanthippe X-ray",
  "Zoro Zapp",
  "Zelda Zeldman",
].map((name, index) => ({
  name,
  phone: `0123456789${index}`,
}));

module.exports = contacts;
